services:
  navidrome:
    image: deluan/navidrome:latest
#    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      ND_LOGLEVEL: debug
      ND_ENABLESHARING: false
    volumes:
      - "./data:/data"
      - "./music:/music:ro"
    networks:
      internal:
        aliases:
         - navidrome.s2.internal

  navidrom-api-auth-proxy:
    labels:
      - com.centurylinklabs.watchtower.scope=autonom
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./.htpasswd:/etc/nginx/.htpasswd
    restart: unless-stopped
    depends_on:
      - navidrome
    networks:
      internal:
  mitmproxy:
    stdin_open: true
    tty: true
    ports:
    - 80:8080
    - 127.0.0.1:8081:8081
    image: mitmproxy/mitmproxy
    command: mitmweb --web-host 0.0.0.0 --mode reverse:http://navidrom-api-auth-proxy
    networks:
      internal:

networks:
  internal:
volumes:
  data-cache:
